version: '2'

services:
  php:
    build: ./php
    volumes:
      - ./src/my-app:/var/www

  nginx:
    image: nginx
    ports:
      - "8044:80"
    volumes:
      - ./src/my-app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=mysql
    links:
      - mysql
    ports:
      - 8080:80
    volumes:
      - /sessions
